### PR TITLE
libextobjc: Move from octest to xctest.

### PR DESCRIPTION
**Pull request by barakwei**
Before we do the keypath thing, we have some time to enable CI on this repo.
Wanna enable circle on this repo and I'll all the config file in this PR?

### CODE REVIEW

**Comment by StatusReport** [comment]
I've set it up. Do you want me to merge this and then to play with Circle, or to do it in one shot?

**Comment by barakwei** [comment]
Let's do it here so I can see it works. I'll copy the circle config from Mantle. We also need to move ReactiveObjC to circle 2.0.

**Comment by StatusReport** [comment]
Yup, we need to move everything to 2.0.

**Comment by barakwei** [comment]
Works like a charm. Let's merge.

**Pull request merged**
