### PR TITLE
metamacros: add more arguments to metamacro_foreach.

### PR DESCRIPTION
**Pull request by ashabtay**

### CODE REVIEW

**Comment by StatusReport** [comment]
Commit title is ambiguous, can you change to `Add more arguments to metamacro_foreach.` or something of that sort?

Otherwise LGTM.

**Comment by ashabtay** [comment]
Changed commit name.

**Comment by StatusReport** [comment]
Remove extra `.` in the comment name :)

**Comment by ashabtay** [comment]
It was already removed before you commented about it

**Comment by StatusReport** [comment]
Nope, still `metamacros: add more arguments to metamacro_foreach..`

**Comment by ashabtay** [comment]
Done

**Pull request merged**
